MAP_SIZE = 'small'
FRAMES_START = 0
FRAMES_STOP = 150
NUM_WAVES_1 = 5
NUM_WAVES_2 = 5
WAVES_STEPS_P_CYCLE = 60
SPLASH_STEPS_P_CYCLE = 50

EXPLOSION_WIDTH = 20
EXPLOSION_HEIGHT = 10
SMOKE_R_F_FRAMES = 10
SMOKA_FRAMES = 200
SAIL_CYCLES = 3