MAP_SIZE = 'small'
# MAP_SIZE = 'big'
FRAMES_START = 0
FRAMES_STOP = 200
# NUM_WAVES_1 = 5
# NUM_WAVES_2 = 5
WAVES_STEPS_P_CYCLE = 60  #
SAIL_STEPS_P_CYCLE = 150
SAIL_CYCLES = 2
SPLASH_STEPS_P_CYCLE = 100
NUM_SPLS = 2  # num per type.
NUM_WAVES = 3  # NUM per type.

EXPLOSION_WIDTH = 20
EXPLOSION_HEIGHT = 10
SMOKE_R_F_FRAMES = 50
SMOKA_FRAMES = 200
